### ISSUE TITLE
The autocompletion panel should prefer the south positon

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-mention#37]
Instead, it prefers the north position:

![image](https://user-images.githubusercontent.com/156149/55542298-08f0f300-56c7-11e9-8c30-4bb8176574d3.png)

**Comment by Reinmar** [comment]
cc @dkonopka @oleq  For me it was intuitive that the panel should display below the text. So does happen e.g. here on GH. But in some apps, where it sticks to the editing field and not the caret (e.g. Slack), it's displayed above. I consider this a different case, but wanted to verify it with you.

**Comment by oleq** [comment]
[The positioning algorithm has the `limiter` defined as editable element.](https://github.com/ckeditor/ckeditor5-mention/blob/master/src/mentionui.js#L421-L431)

It chooses one of the available positions which fits the panel within the editable rectangle the most. If none of the positions fits perfectly into the editable, the one with the greatest intersection area is chosen. 

We can remove the custom limiter restriction so then the positions are 
* matched against the greatest intersection area with the viewport
* considered in the order of preference

@jodator Why the limiter in the first place, BTW? Does it have a specific role, or fixes a specific case?

**Comment by jodator** [comment]
I was struggling with consistent behavior of the positioning algorithm and during some test it turned out to be working well. Later the problem (stick to the firstly chosen position) was solved by reading the `panelView.position` IIRC. The limiter make sense also to position the mention panel with the consideration of the editing area.

**Comment by jodator** [comment]
> considered in the order of preference

I'd remove the `limiter` and probably this should sort out the problem.

**Comment by jodator** [comment]
I was debugging why the balloon is choosing the north position where there's clearly a place to the south of cursor?

Because it does better fit in the default limiter (`document.body`):

![Selection_297](https://user-images.githubusercontent.com/247363/55875164-a4d1a180-5b94-11e9-8059-17fa6649bbc4.png)

So using the default limiter (`document.body`) should play along with features that shrinks the document body (looking at you ckeditor5 inspector) but will produce "wrong" results for short content.

@oleq Are we OK with this? Using the default limiter (`document.body`) on manual test would probably need some fixes in manual tests.

**Comment by oleq** [comment]
> So using the default limiter (`document.body`) should play along with features that shrinks the document body (looking at you ckeditor5 inspector) but will produce "wrong" results for short content.

Well... a short body (shorter than the viewport) and the editor being the last child (or so) and inserting around at the bottom of the editable does sound like an edge case to me. Developers can easily fix that by expanding `<body>` using CSS (`html, body{ min-height:100%; }`).

As for the inspector and other floating elements that could clash with the panel, AFAIR there's no API that would help us resolve this issue out–of–the–box. We would need to exclude those elements from the area available for the panel to position itself and, in fact, [we have an issue for that](https://github.com/ckeditor/ckeditor5-ui/issues/460).

**Comment by Reinmar** [comment]
Did #52 actually change anything? I don't see any change in the behaviour.

**Comment by jodator** [comment]
It's done inline with this comment: https://github.com/ckeditor/ckeditor5-mention/pull/52#issuecomment-484852365 & https://github.com/ckeditor/ckeditor5-mention/pull/52#issuecomment-485811986.
The mention UI prefers south position and is constrained within editing area. So the issue as such was considered invalid.

**Comment by Reinmar** [comment]
Please show me on screenshots what has changed because I can't figure that out myself.

**Comment by jodator** [comment]
It depends on the editor size, the body size and the position of the content.

The logic behind it doesn't changed as of the comments I've posted - we are not forcing the south position in every case - ie when the editor body is short because we prefer to constrain the UI withing editor (editing area) then overlaping content.

So most interesting static cases (first open):

1. Big editor, mention inside text (prefer south)

![Selection_013](https://user-images.githubusercontent.com/247363/58487894-acf79780-8168-11e9-9028-5bb7831d432c.png)

2. Narrow editor - height of editing area < mention ui height  (prefer south)

![Selection_016](https://user-images.githubusercontent.com/247363/58488075-06f85d00-8169-11e9-9c49-f3886998f928.png)

3. Big editor - end of content (prefer editing area)
![Selection_015](https://user-images.githubusercontent.com/247363/58487933-c1d42b00-8168-11e9-93c9-0d7fd458c71a.png)

Now the dynamic behavior (first open, then typing):

1. Big editor, mention inside text (prefer south - stays south
![Peek 2019-05-28 16-55](https://user-images.githubusercontent.com/247363/58488359-80904b00-8169-11e9-991d-9f504bc1e72e.gif)
)

2. Narrow editor (starts south - stays south)
![Peek 2019-05-28 16-56](https://user-images.githubusercontent.com/247363/58488414-9d2c8300-8169-11e9-8a2c-fc7f0066c70f.gif)

3. Big editor - end of content (starts north
![Peek 2019-05-28 16-57](https://user-images.githubusercontent.com/247363/58488513-bfbe9c00-8169-11e9-8703-3817c6ff35e5.gif)
 - stays north)

4. Similar as 3 but starts with smaller UI (mention ui fits south) - starts south - stays south
![Peek 2019-05-28 16-59](https://user-images.githubusercontent.com/247363/58488635-fdbbc000-8169-11e9-9c86-c0c14178cbb0.gif)


This is for manual tests. For documention pages the behavior might be slightly different due to different sizes of the editor and pages AFAICS. So the calculations of "best" area [might be dependent on the content around the editor](https://github.com/ckeditor/ckeditor5-mention/issues/37#issuecomment-481653792) (I've added some text in the body so the issue from that comment wouldn't affect screencasts.

**Comment by Reinmar** [comment]
Interesting – I couldn't get the same results in the documentation. This panel chooses the north position unless there's space in the editor below the caret.

Actually... it looks broken. Why does it pick the north here:

![image](https://user-images.githubusercontent.com/156149/58537247-cfce8e00-81f2-11e9-995c-90b1bd80146d.png)

When it picks the south here (when there's still not enough space):

![image](https://user-images.githubusercontent.com/156149/58537259-d4934200-81f2-11e9-80b5-404e8847152a.png)

It doesn't seem to work reliably.

**Comment by jodator** [comment]
Well I'd argue that it does ;)

The docs have different CSS styles and the rendered line is bigger. I've added logging to the `getBestPosition()` which calculates which position from a set is the best given the criteria. For mentions we provide `limiter` - in this case an editing area (as other features) and the ContextualPanel (or Ballon I don't remember now) sets the `fitInViewport` to `true`. So the best position is that which fits most in the viewport and in the editing area.

Now for the same content look how it calculates the best position:
![Selection_019](https://user-images.githubusercontent.com/247363/58544070-e1b72d80-8200-11e9-9492-7a93025b2dc6.png)

I screenshot above I've logged each step of internal `positions.each()` call (I've also logged the return condition but is always falsy as it not fully displayed in the limiter).
As you can see positions are evaluated: `caret_se > caret_sw > caret_ne > caret_nw` (hence the "prefer south" is valid here). Now for each position the algorithm checks how mention UI will be contained in `VP` viewport & `LIM` limter area - editing area.

In the docs the editor have different line heigts and it turns out that `caret_ne` is slightly better contained in the limiter area then `caret_se` by 316 square pixels (~3.6%) which is pretty marginal but is bigger.

**Comment by Reinmar** [comment]
Hm... I think I realized what caused my confusion – I thought that we consider only the editable area for the limiter. But it seems that the toolbar is also considered as a part of the preferred area... which is a bit counterintuitive for me.

The other thing which I didn't get is that we compare areas and choose the biggest one. I thought that it works differently – try to use the first position, if not acceptable (doesn't fit), check the next one. What's important is that in the screenshots I posted above the panel doesn't fit in the limiter regardless of its placement. I'd expect that if it doesn't fit, we prefer S. But sometimes it chooses S and sometimes N because, as you explained, we compare only areas. 

The current solution behaves kinda like an unstable sorting algorithm. Sometimes you'll get this, sometimes that. If you don't know the algorithm, you don't understand as a user why you got something else than a second before for nearly the same initial situation.

**Comment by jodator** [comment]
> Hm... I think I realized what caused my confusion – I thought that we consider only the editable area for the limiter. But it seems that the toolbar is also considered as a part of the preferred area... which is a bit counterintuitive for me.

No. We consider the editing area - not whole editor with toolbar: https://github.com/ckeditor/ckeditor5-mention/blob/711ebbac96d05153b175d4d47964903ba4c536a6/src/mentionui.js#L524-L534

The editing area in the docs is bigger then in manual tests:

![editorheights](https://user-images.githubusercontent.com/247363/58548267-41b1d200-8209-11e9-8a47-34eeaf6b8b42.png)

> The other thing which I didn't get is that we compare areas and choose the biggest one. I thought that it works differently – try to use the first position,

The algorithm works this way only if the whole panel is contained withing limiter. In here it does not so we evaluate all positions to find the best - see the "is fully displayed: false" in the logs.

On your screens shots you have editors of different height (3 lines vs 4 lines). So on the second one it chooses south as it is better contained within editing area the other positions (namely north). On the first one it chooses north because of slightly (3.63% as calculated above) bigger area of fit in editing area.
