### ISSUE TITLE
Cannot type mention inside brackets, quotes and after a soft break

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-mention#44]
Try to open mention's feed after typing `(@`. At this moment it does not work.

**Comment by oleq** [comment]
The feature has been implemented so far to prevent triggering in the middle of the word (`foo@trigg.er`). 

IMO we need to whitelist certain structures, like for instance

```
\s[
    \[\("'-
]@
````

to allow typing `(@foo)`, `[@foo]`, `"@foo"`, `'@foo'` etc..

**Comment by jodator** [comment]
Also `<softBreak>foo` might not work now.

**Comment by jodator** [comment]
I've implemented this in a simple/naive way - just by adding some arbitrary characters to the regex:

```js
const IGNORED_CHARACTERS = ' ([{\'"';
```
The implementation (hence const name) is secondary to my comment here so keep this in mind.

There are couple of issues here:

1. Typing after `<softBreak>` is not working - :bug:
2. Typing after an inline element (defined in schema as `isInline = true`) - right now I see that you might require a space after an inline widget and I'd left this as-is
3. Typing inside quotes/parenthesis - kinda feature to me not a :bug: - so I'd like to open a discussion for this.

---

So ATM I've used reported characters to enable this feature and as stated above it is very naive approach. 

_Note_: The Mention feature only interprets text before caret so only opening parenthesis/quotes are taken under consideration.

The full-blown approach should allow **every** [opening punctuation](https://www.compart.com/en/unicode/category/Ps). The hand-crafted regex for this will be ugly since JavaScript RegExp engine does not support [Unicode categories](http://www.unicode.org/reports/tr44/#GC_Values_Table):

```js
const regex = new Regex( '\\(\\[\\{\u0F3A\u0F3C\u169B\u201A\u201E\u2045\u207D\u208D\u2308\u230A\u2329\u2768\u276A\u276C\u276E\u2770\u2772\u2774\u27C5\u27E6\u27E8\u27EA\u27EC\u27EE\u2983\u2985\u2987\u2989\u298B\u298D\u298F\u2991\u2993\u2995\u2997\u29D8\u29DA\u29FC\u2E22\u2E24\u2E26\u2E28\u2E42\u3008\u300A\u300C\u300E\u3010\u3014\u3016\u3018\u301A\u301D\uFD3F\uFE17\uFE35\uFE37\uFE39\uFE3B\uFE3D\uFE3F\uFE41\uFE43\uFE47\uFE59\uFE5B\uFE5D\uFF08\uFF3B\uFF5B\uFF5F\uFF62' );
```
while other languages [we have access to unicode group switches](https://www.regular-expressions.info/unicode.html):

```php
preg_match( '/\p{Ps}/', '[', $out );
```

@mlewand / @Reinmar: 
So the question here is: Do we want to support them all or only some arbitrary subset of this group?

ps.: I've alredy talked with @oleq and we came to a conclusion that sooner or later we will need an util for creating unicode regexes.

**Comment by mlewand** [comment]
I just checked the state of things.

Support for the unicode category escape character has been introduced in es2018 and it is already supported by Chrome and Safari. [Ticket for support in FireFox](https://bugzilla.mozilla.org/show_bug.cgi?id=1361876) is pending and is [blocked on irregexp bump issue in FF](https://bugzilla.mozilla.org/show_bug.cgi?id=1367105) but it should come sooner than later.

It is possible very easily to feature detect it:

* Edge throws `Invalid regular expression: invalid escape in unicode pattern` when constructing `RegExp( /\p{Letter}/u )`.
* Firefox throws `SyntaxError: invalid identity escape in regular expression` when constructing `RegExp( /\p{Letter}/u )`.

Given that it is already specified and it is a matter of time when it gets to FF (and Edge is migrating to Blink) I would implement it based on a feature detection. If unicode category escape is available, use it to provide best experience and full utf support (same thing might apply to #38). In case it is not supported by the client, we fall back to naive behavior, in this case simplified handcrafted regexp.

I don't see a need to intrudce an extra dependency for that (xRegExp).

**Comment by mlewand** [comment]
To sum up, the fix uses two strategies:

* generic for browsers that are lacking regexp group support - you can a mention after list of predefined characters like `(`, `[`, `"`, `'`.
* full for modern browsers that support regexp groups (today Chrome only) and in addition to above it supports fancy utf quotes like `“` `‘` etc.
